title: Xue Yuquan's Homepage
page-top-title: AI & Robotics
top-section-bg-text: Xue Yuquan
home-subtitle: Xue Yuquan&ensp;|&ensp;薛雨泉
copyright-text: '&copy; Xue Yuquan 2024-2025. All Rights Reserved.'
